### ISSUE TITLE
How to you use

### ISSUE THREAD

**Issue by isularifin** [mcfarljw/cordova-plugin-sound#1]
hi, how do i use this plugin? Is this work for html5 audio tag? Thanks

**Comment by mcfarljw** [comment]
No, this plugin is only for playing very short sound files on Android and iOS. I haven't spent much time documenting it, but the general plugin syntax is here:

https://github.com/mcfarljw/cordova-plugin-sound/blob/master/www/sound.js

**Comment by isularifin** [comment]
thanks alot
